version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: ecommerce-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ecommerce-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
